version: 1.2
workflows:
  - name: Nomadic
    subclass: WDL
    primaryDescriptorPath: /Nomadic.wdl
    readMePath: /Nomadic.README.md
    testParameterFiles:
      - /Nomadic.wdl

  - name: SnTestWdl
    subclass: WDL
    primaryDescriptorPath: /SnTestWdl.wdl
    readMePath: /Nomadic.README.md
    testParameterFiles:
      - /SnTestWdl.wdl
