version: 1.2
workflows:
  - name: Nomadic
    subclass: WDL
    primaryDescriptorPath: /Nomadic.wdl
    readMePath: /Nomadic.README.md
    testParameterFiles:
      - /Nomadic.wdl

  - name: NomadicSummary
    subclass: WDL
    primaryDescriptorPath: /NomadicSummary.wdl
    readMePath: /NomadicSummary.README.md
    testParameterFiles:
      - /NomadicSummary.wdl